### PR TITLE
Upgrade commons-io

### PR DESCRIPTION
**Pull request by postalservice14**
Your commons-io version is very old and is conflicting with other libraries we have.  Any chance for an upgrade?

### CODE REVIEW

**Comment by hzalaz** [comment]
@postalservice14 we'd need to check if something breaks first. I believed the dependencies where bundled in the same jar for this library so how it's conflicting with other libraries?

**Comment by postalservice14** [comment]
In maven `auth0-spring-security-api:0.3.0` requires `java-jwt:2.2.0` which requires `org.apache.commons:commons-io` which is conflicting with another library that requires `commons-io:commons-io:2.5`

For our tests to pass and our application to work we had to add an exclusion in the pom like this:
```xml
<dependency>
    <groupId>com.auth0</groupId>
    <artifactId>auth0-spring-security-api</artifactId>
    <version>0.3.0</version>
    <exclusions>
        <exclusion>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-io</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

I'm not entirely sure what you're asking, but what I do know is that the old dependency on this library is causing issues for us.  Also, I guess it goes without saying, that `auth0-spring-security-api` will need to be updated to pull in the new version of `java-jwt` as well for it to fully solve our problem.

**Comment by hzalaz** [comment]
We are using the shade plugin to repackage the dependencies inside a java-jwt jar https://github.com/auth0/java-jwt/blob/master/pom.xml#L115 (not something I'd like but it's how it's built) so it should not fetch them and break your build.

However, recently there was a PR to use change the commons-io groupId and that was not updated in the plugin. Will try to test the new commons-io version next week.

**Comment by postalservice14** [comment]
Ahh, yeah, I see, the groupId was changed the shade plugin not work.  Looks like your shade plugin is still looking for `org.apache.commons.io`.

Thanks.

**Comment by adrogon** [comment]
@postalservice14 This has already been changed in java-jwt:2.2.1, but they haven't released an auth0-spring-security-api:0.3.1 that would contain that dependency change.
What you can do is add a dependency to java-jwt:2.2.1 in your project, or wait 0.3.1 to be released.

**Comment by hzalaz** [comment]
@adrogon the PR updates commons-io to version 2.5

**Comment by hzalaz** [comment]
will close this one and update the shade plugin to avoid the clash.

**Pull request closed without merging**
