### PR TITLE
Update to Gradle 6.1.1

### PR DESCRIPTION
**Pull request by jimmyjames**
### Changes

Updates to Gradle 6.1.1 and the latest OSS plugin.

### Testing

No test changes or impacts.

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [X] All existing and new tests complete without errors

### CODE REVIEW

**Comment by lbalmaceda** [comment]
which CH label suits best this?

**Comment by jimmyjames** [comment]
> which CH label suits best this?

I think `CH: Changed`.

**Comment by PaulDaviesC** [comment]
@jimmyjames Any timeline by which this will be released?

**Comment by lbalmaceda** [comment]
@PaulDaviesC If not today the next week 👍

**Pull request merged**
