### PR TITLE
Changed ObjectMapper configuration for deployment on Dell Boomi Cloud platform

### PR DESCRIPTION
**Pull request by mennodehaas**
Dell Boomi does not allow java to override access modifiers when using reflection. Therefore, added the following ObjectMapper configuration in the JWTParser.java class:

mapper.configure(MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS, false);

Unit tests are running successfully.

### CODE REVIEW

**Comment by lbalmaceda** [comment]
That flag doesn't seem harmful so I'm fine with it. [docs](https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/MapperFeature.html#CAN_OVERRIDE_ACCESS_MODIFIERS)

But please, remove all the files in the PR and keep only the actual change in `JWTParser`. They are related to the IDE you're using. You can include these rules in the .gitignore file to prevent it. https://www.gitignore.io/api/eclipse

**Comment by mennodehaas** [comment]
Changed PR with 1 source file that has been changed.

**Comment by mennodehaas** [comment]
Modified the pull request. Why has the PR not been processed yet?

**Comment by mennodehaas** [comment]
When will this one been processed?

**Comment by lbalmaceda** [comment]
I was waiting for the codecov checks to pass, but as far as I see something is broken and the upload fails if the last commit on the PR is part of a rebase.

Checking again the documentation on that flag it points out possible performance issues. I'll need to assert this impact before merging the PR.
> Note that this setting may have significant performance implications, since access override helps remove costly access checks on each and every Reflection access. If you are considering disabling this feature, be sure to verify performance consequences if usage is performance sensitive

**Comment by lbalmaceda** [comment]
@mennodehaas any feedback/clue on the performance impact this flag has?

@skjolber While that can work and will be the preferred option for many devs, we don't want to expose external libraries' classes on the public API.

**Comment by mennodehaas** [comment]
@lbalmaceda I created a quick performance benchmark on my machine generating 10.000 tokens and decoding 10.000 tokens.

java-jwt-3.3.0 release
Generated 10000 tokens in 1126 ms (0.1126 ms per token)
Decoded 10000 tokens in 964 ms (0.0964 ms per token)

java-jwt-3.3.0 release with mapper.configure(MapperFeature.CAN_OVERRIDE_ACCESS_MODIFIERS, false);
Generated 10000 tokens in 1238 ms (0.1238 ms per token)
Decoded 10000 tokens in 859 ms (0.0859 ms per token)

**Comment by skjolber** [comment]
I'll share a JMH project later today for benchmarks / experiments. I suspect the impact of this issue will be low.

**Comment by skjolber** [comment]
@mennodehaas try measuring using this: https://github.com/skjolber/java-jwt-benchmark
First run 

./gradlew clean build  publishToMavenLocal

on the modified java-jwt project.

**Comment by mennodehaas** [comment]
@skjolber what are the results? I don't have experience running JMH benchmarks.

**Comment by skjolber** [comment]
Seems the performance impact is low, under a percent.

**Comment by mennodehaas** [comment]
What is the progress on this PR?

**Pull request closed without merging**
