### PR TITLE
added date validation dedicated exception

### PR DESCRIPTION
**Pull request by Spyna**
for issue https://github.com/auth0/java-jwt/issues/153

### CODE REVIEW

**Comment by hzalaz** [comment]
Thanks for the PR @Spyna can you try to reduce the diff the PR has, e.g. avoid reordering the class elements since its hard to tell what you changed?

**Comment by Spyna** [comment]
@hzalaz I' ve restored the original order. 
The modified method is `assertValidDateClaim`

**Comment by lbalmaceda** [comment]
Hi @Spyna 
Thanks for the changes. We think it should throw a specific Exception _only_ in case the `exp` claim is invalid: lets call that `TokenExpiredException` and make it extend `JWTVerificationException`, as it's not that the claim it's invalid but rather that the token was ok but it has expired. Also let's keep the `InvalidClaimException` in case of invalid `nbf` and `iat` claims. Sounds good to you?

The changes should be done in the `assertValidDateClaim` method: When the boolean is true means we are here for the `exp` claim, and if it's invalid we should throw this new exception type. When the boolean is false, means it's one of the other two claims and if it's invalid we should throw the old exception. You can also split the method in 2 and handle these scenarios in a separate way if you want. Please make sure to add/update the tests to check the new exception.

Cheers

**Comment by Spyna** [comment]
Sounds great to me, 
I'll modify the code and push, 

thank you

**Comment by lbalmaceda** [comment]
@Spyna Please rollback the code formating changes in order to leave a clearer diff of the `JWTVerifier` class. Besides that it's looking fine. Thanks

**Pull request merged**
