### PR TITLE
Support to add objects (primitive and collection) as claim in token pa…

### PR DESCRIPTION
**Pull request by complanboy2**
…yload

As requested @gustavoamigo we are giving support to add objects if primitive and collection types as claim in token payload.

Followed the suggestion by @lbalmaceda to make this change.
https://github.com/auth0/java-jwt/pull/164#issuecomment-295764851

### CODE REVIEW

**Comment by complanboy2** [comment]
@lbalmaceda waiting for your review. Please review at your free time.

**Comment by complanboy2** [comment]
> The added `withClaim()` method is not type safe, and it is not possible to overload it due to type erasure. Also, nested collections would be raw types, so there would be no guarantee as to the types they would contain.
> 
> A reasonable compromise may be to accept only primitive wrapper types, `Set`s and `List`s and to call `toString()` on anything else. That would require `instanceof` checks at runtime which may be ugly.

Hi @martinoconnor , thank you for the reivew. It helped fixing it better.
Please review the updated code when you have time.

**Comment by ornom0n** [comment]
Hello,

Adding this feature would allow me to migrate to JWT 3 as one of the claims we use is a Map and that cannot be changed. Is anything pending here?

**Comment by complanboy2** [comment]
> Hello,
> 
> Adding this feature would allow me to migrate from JWT 2 to JWT 3 as one of the claims we use is a Map and that cannot be changed. Is anything pending here?

Hi OrnomOn,

I'm waiting on review, once the review is done, we are good to merge.
If it is helpful to you, please go ahead with the use. And please have a look at checks once, though major are passed.

**Comment by complanboy2** [comment]
Any hope for getting this reviewed and also please check, #297 as well.

**Pull request closed without merging**
